spring:
  application:
    name: vega.news

logging:
  level:
    com.vega.news: INFO

upstox:
  instrument-path: /root/news/data/instruments/upstox/upstox.json
  auth:
    file: /root/news/auth/upstox/auth.upstox.json

news:
  refresh:
    interval: 15m
  retention:
    days: 3650
  upstox:
    page-size: 100
  storage:
    root: /root/news/storage/news
    holdings-view: /root/news/storage/news/holdings.jsonl
    positions-view: /root/news/storage/news/positions.jsonl
